-- #1 create database
DROP DATABASE IF EXISTS user_s;
DROP USER IF EXISTS user_s;

CREATE USER user_s WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    CREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'user_s';

CREATE DATABASE user_s
    WITH OWNER = user_s
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT CONNECT ON DATABASE user_s TO user_s;